services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    container_name: app-next
    ports:
      - '3334:3334'
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
